// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单个 fclass 的 edge/depth 调参规格（默认值 + 推荐范围）。
 *
 * 范围上界可能为无穷（sea）；JSON 无法表示 Infinity，故用 `Option<f64>`（`null` = ∞）。
 */
export type EdgeGuidanceItem = { fclass: string, edge: number, depth: number, edgeMin: number, edgeMax: number | null, depthMin: number, depthMax: number | null, };
