// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单个 fclass 的 edge/depth 覆盖值（来自前端齿轮子窗口）。
 */
export type EdgeOverride = { fclass: string, edge: number, depth: number, };
